### ISSUE TITLE
add operator == and hashcode

### ISSUE THREAD

**Issue by denniskaselow** [isoos/bit_array#1]
Currently it's not possible to compare two `BitArray`s (and the other BitSets too).

As a workaround I cloned the repository and added the auto-generated methods.
```dart
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BitArray &&
          runtimeType == other.runtimeType &&
          _data == other._data;

  @override
  int get hashCode => _data.hashCode;
```

**Comment by isoos** [comment]
Are you sure that these are correct? I have some doubts about it, but would accept a PR if it is with tests.

**Comment by denniskaselow** [comment]
What are your doubts? In the end, it's just the == and hashCode of the underlying Uint64List.

But I just realized I can't use BitArray anyway because Uint64List isn't supported in the browser.

**Comment by isoos** [comment]
The documentation of `Uint64List` does not indicate that it supports `==` and `hashCode` consistently (nor its source).

**Comment by denniskaselow** [comment]
Yep, doesn't work and I should have seen it when I opened this bug as my own tests still didn't change to green..

Had to iterate over all elements of `_data` after all.

I am now using a minimal implementation of BitSet for my use case using a Uint32List. Feel free to close this issue.

**Comment by isoos** [comment]
If you think it is useful, we could backport your changes with Uint32List to this package. Either by adding a new class there, or porting the current ones to use 32-bit ints. Do you happen to have performance benchmarks how it may affect the performance on the Dart VM?

**Comment by denniskaselow** [comment]
There are a few more changes required to switch from `Uint64List` to `Uint32List`, like the `toUint64Iterable` on `BitSet` (and the `0xffffffffffffffff` in `_IntIterator`). No need to break your API just for me, as I'm fine now.

And no, I don't have performance benchmarks, just a few calls to `Stopwatch` in my actual code that I wouldn't call a performance benchmark and the Chrome performance tab that told my that my use of `BigInt` instead of a `BitSet` wasn't that performant.

This is what I did (removed everything I do not need, and changed the behavior of some methods):
https://github.com/denniskaselow/dartemis/blob/master/lib/src/core/utils/bit_set.dart

**Comment by isoos** [comment]
@denniskaselow I wanted this library to work in the browser too, and if it does not work properly, I think the breaking change is not too bad to do. If you have the change prepared, I am happy to accept PRs. It will be released with a different major release though.

**Comment by denniskaselow** [comment]
Okay, I created https://github.com/isoos/bit_array/pull/2 for the change from Uint64List to Uint32List.
