### ISSUE TITLE
Optimize length changing

### ISSUE THREAD

**Issue by yanivshaked** [isoos/bit_array#6]
Instead of reallocating the list every time the length changes:

```
set length(int value) {
    if (_length == value) {
      return;
    }
    final data = Uint32List(_bufferLength32(value));
    data.setRange(0, math.min(data.length, _data.length), _data);
    _data = data;
    _length = _data.length << 5;
  }
```

You could check if _bufferLength32(value) has changed, and reallocate only then. This can dramatically reduce the allocations in case the list is build incrementally:

```
set length(int value) {
    if (_bufferLength32(_length) == _bufferLength32(value)) {
      return;
    }
    final data = Uint32List(_bufferLength32(value));
    data.setRange(0, math.min(data.length, _data.length), _data);
    _data = data;
    _length = _data.length << 5;
  }
```

What do you think?

**Comment by isoos** [comment]
I'd still keep the `_length == value` check, but I don't mind the additional one. Would you care to do a PR?

**Comment by yanivshaked** [comment]
Sure, will create a PR

**Comment by yanivshaked** [comment]
Thanks for the quick merge
